### ISSUE TITLE
Category for tool-bar

### ISSUE THREAD

**Issue by jerone** [bastilian/atom-packages.directory#2]
I like to propose a new category for the [tool-bar](https://atom.io/packages/tool-bar) package by grouping all tool-bar [plugins](https://github.com/suda/tool-bar#plugins) with the [`tool-bar`](https://atom.io/packages/search?utf8=%E2%9C%93&q=keyword%3Atool-bar) keyword.

**Comment by bastilian** [comment]
There is currently http://atom-packages.directory/category/navigation-toolbar/ (see https://github.com/bastilian/atom-packages.directory/blob/master/config.yml#L318) It is under Navigation. I think there may be a need to expose UI components and tweaks better.

**Comment by jerone** [comment]
> There is currently...

Ah thanks!

I was going to open an issue about incorrect counts, until I noticed the sub-categories. Maybe those can be designed better by separating them more from the package headers.
